apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-nextcloud
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nextcloud.labels" . | nindent 4 }}
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    {{- include "nextcloud.selectorLabels" . | nindent 4 }}
