apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  namespace: {{ include "environment.namespace" . }}
  labels:
    {{- include "redis.labels" . | nindent 4 }}
type: Opaque
data:
  postgres-password: {{ .Values.secrets.postgres.password | b64enc }}
  redis-password: {{ .Values.secrets.redis.password | b64enc }}
  nextcloud-admin-password: {{ .Values.secrets.nextcloud.adminPassword | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-postgres-secrets
  namespace: {{ include "environment.namespace" . }}
  labels:
    {{- include "postgresql.labels" . | nindent 4 }}
type: Opaque
data:
  postgres-password: {{ .Values.secrets.postgres.password | b64enc }}
  postgres-user: {{ .Values.secrets.postgres.user | b64enc }}
  postgres-db: {{ .Values.secrets.postgres.db | b64enc }}
